name: SpringBoot Pipeline

on: 
  push:
    branches:
      - main
      - dev
      - feature*
  pull_request:
    branches: ["main", "dev"]

jobs:
  Checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4